In [2]:
# ML_in_Finance-Deep-Learning-Interpretability
# Author: Matthew Dixon
# Version: 1.0 (08.09.2019)
# License: MIT
# Email: matthew.dixon@iit.edu
# Notes: tested on Mac OS X with Python 3.6 and Tensorflow 1.3.0
# Citation: Please cite the following reference if this notebook is used for research purposes:
# Bilokon P., Dixon M.F. and I. Halperin, Machine Learning in Finance: From Theory to Practice, Springer Graduate textbook Series, 2020. 

In [2]:
import random
import pandas as pd
import numpy as np
import seaborn as sns
import math
from datetime import datetime
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from keras.regularizers import l1,l2
from keras.callbacks import EarlyStopping
from keras.wrappers.scikit_learn import KerasRegressor, KerasClassifier
from sklearn.model_selection import KFold, StratifiedKFold, GridSearchCV, cross_val_score, train_test_split
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
from sklearn import metrics
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import statsmodels.api as sm
import statsmodels.stats.diagnostic as tds
from statsmodels.api import add_constant
from scipy import stats


Using TensorFlow backend.


# Simple Data Generation Process (DGP)

$Y=X_1+X_2 + \epsilon, ~X_1, X_2, \epsilon \sim N(0,1)$

In [7]:
M = 5000 # Number of sample 
np.random.seed(7) # set the seed for reproducebility of results
X = np.zeros(shape=(M,2))
X[:int(M/2),0]= np.random.randn(int(M/2))
X[:int(M/2),1]= np.random.randn(int(M/2))

X[int(M/2):,0]= -X[:int(M/2),0]
X[int(M/2):,1]= -X[:int(M/2),1]


eps= np.zeros(shape=(M,1))
eps[:int(M/2)]= np.random.randn(int(M/2),1)
eps[int(M/2):]=-eps[:int(M/2)]
Y= 1.0*X[:,0] + 1.0*X[:,1] + eps

In [9]:
np.mean(X,axis=0)

array([-2.37365683e-17, -5.48450174e-18])

# Use OLS to fit the model to the data

In [7]:
ols_results = sm.OLS(Y, sm.add_constant(X)).fit()

In [8]:
y_ols=ols_results.predict(sm.add_constant(X))

In [9]:
ols_results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.673
Model:                            OLS   Adj. R-squared:                  0.673
Method:                 Least Squares   F-statistic:                     5150.
Date:                Wed, 11 Sep 2019   Prob (F-statistic):               0.00
Time:                        10:12:00   Log-Likelihood:                -7041.3
No. Observations:                5000   AIC:                         1.409e+04
Df Residuals:                    4997   BIC:                         1.411e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0040      0.014      0.289      0.773      -0.023       0.031
x1             0.9905      0.014     70.447      0.000       0.963       1.018
x2             1.0038      0.014     71.306      0.000       0.976       1.031
==============================================================================
Omnibus:                        0.693   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.707   Jarque-Bera (JB):                0.643
Skew:                          -0.020   Prob(JB):                        0.725
Kurtosis:                       3.039   Cond. No.                         1.02
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Compare with a ffwd neural network with no hidden layers

In [10]:
def linear_NN0_model(l1_reg=0.0):    
    model = Sequential()
    model.add(Dense(1, input_dim=2, kernel_initializer='normal')) #, activation='None'))
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae', 'mse'])
    return model

In [20]:
es = EarlyStopping(monitor='loss', mode='min', verbose=1, patience=10)

In [21]:
lm = KerasRegressor(build_fn=linear_NN0_model, epochs=40, batch_size=10, verbose=1, callbacks=[es])

In [22]:
lm.fit(X,Y)

Epoch 1/40
5000/5000 [==============================] - 1s 110us/step - loss: 2.3364 - mean_absolute_error: 1.2173 - mean_squared_error: 2.3364
Epoch 2/40
5000/5000 [==============================] - 0s 76us/step - loss: 1.4649 - mean_absolute_error: 0.9681 - mean_squared_error: 1.4649
Epoch 3/40
5000/5000 [==============================] - 0s 76us/step - loss: 1.1140 - mean_absolute_error: 0.8436 - mean_squared_error: 1.1140
Epoch 4/40
5000/5000 [==============================] - 0s 76us/step - loss: 1.0072 - mean_absolute_error: 0.8021 - mean_squared_error: 1.0072
Epoch 5/40
5000/5000 [==============================] - 0s 76us/step - loss: 0.9837 - mean_absolute_error: 0.7918 - mean_squared_error: 0.9837
Epoch 6/40
5000/5000 [==============================] - 0s 80us/step - loss: 0.9800 - mean_absolute_error: 0.7900 - mean_squared_error: 0.9800
Epoch 7/40
5000/5000 [==============================] - 0s 82us/step - loss: 0.9796 - mean_absolute_error: 0.7897 - mean_squared_error: 0.979

## Check that the weights are close to one

In [23]:
lm.model.get_weights()

[array([[0.98592055],
        [1.0046886 ]], dtype=float32), array([0.00421808], dtype=float32)]

# Compare with a FFW Neural Network with one hidden layer (unactivated)


In [24]:
n = 10 # number of hidden units

In [32]:
def linear_NN1_model(l1_reg=0.0):    
    model = Sequential()
    model.add(Dense(n, input_dim=2, kernel_initializer='normal')) 
    model.add(Dense(1, kernel_initializer='normal', activation='linear'))
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae', 'mse'])
    return model

In [33]:
lm = KerasRegressor(build_fn=linear_NN1_model, epochs=50, batch_size=10, verbose=1, callbacks=[es])

In [34]:
lm.fit(X,Y)

Epoch 1/50
5000/5000 [==============================] - 1s 144us/step - loss: 1.5925 - mean_absolute_error: 0.9781 - mean_squared_error: 1.5925
Epoch 2/50
5000/5000 [==============================] - 0s 92us/step - loss: 0.9818 - mean_absolute_error: 0.7901 - mean_squared_error: 0.9818
Epoch 3/50
5000/5000 [==============================] - 1s 105us/step - loss: 0.9818 - mean_absolute_error: 0.7912 - mean_squared_error: 0.9818
Epoch 4/50
5000/5000 [==============================] - 1s 112us/step - loss: 0.9822 - mean_absolute_error: 0.7914 - mean_squared_error: 0.9822
Epoch 5/50
5000/5000 [==============================] - 0s 95us/step - loss: 0.9818 - mean_absolute_error: 0.7919 - mean_squared_error: 0.9818
Epoch 6/50
5000/5000 [==============================] - 1s 114us/step - loss: 0.9822 - mean_absolute_error: 0.7906 - mean_squared_error: 0.9822
Epoch 7/50
5000/5000 [==============================] - 0s 92us/step - loss: 0.9814 - mean_absolute_error: 0.7904 - mean_squared_error: 0.

In [35]:
W1=lm.model.get_weights()[0]
b1=lm.model.get_weights()[1]
W2=lm.model.get_weights()[2]
b2=lm.model.get_weights()[3]
print(W1, W2)

[[-0.28151304  0.33660048 -0.32534724 -0.3117283   0.36416572  0.31704733
  -0.3224496   0.32124516  0.28360805  0.40207058]
 [-0.3099645   0.27803436 -0.37927535 -0.2829823   0.2626483   0.31276977
  -0.3437224   0.31792367  0.37649897  0.31318784]] [[-0.35752591]
 [ 0.33028835]
 [-0.28204554]
 [-0.31195363]
 [ 0.2602262 ]
 [ 0.344295  ]
 [-0.3088067 ]
 [ 0.30915156]
 [ 0.29915127]
 [ 0.27908695]]


## Check that the coefficients are close to one and the intercept is close to zero

In [36]:
beta_0=np.dot(np.transpose(W2), b1) + b2
beta_1=np.dot(np.transpose(W2), W1[0])
beta_2=np.dot(np.transpose(W2), W1[1])

In [37]:
print(beta_0,beta_1,beta_2)

[0.02593422] [1.0006967] [0.9784023]


# Compare with a FFW Neural Network with one hidden layer (tanh activated)

In [39]:
# number of hidden neurons
n=10

In [40]:
# with non-linear activation
def linear_NN1_model_act(l1_reg=0.0):    
    model = Sequential()
    model.add(Dense(n, input_dim=2, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(1, kernel_initializer='normal')) 
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae', 'mse'])
    return model

In [43]:
lm = KerasRegressor(build_fn=linear_NN1_model_act, epochs=100, batch_size=10, verbose=1, callbacks=[es])

In [44]:
lm.fit(X,Y)

Epoch 1/100
5000/5000 [==============================] - 1s 149us/step - loss: 1.6640 - mean_absolute_error: 1.0059 - mean_squared_error: 1.6640
Epoch 2/100
5000/5000 [==============================] - 0s 92us/step - loss: 1.0040 - mean_absolute_error: 0.8007 - mean_squared_error: 1.0040
Epoch 3/100
5000/5000 [==============================] - 0s 92us/step - loss: 1.0032 - mean_absolute_error: 0.8005 - mean_squared_error: 1.0032
Epoch 4/100
5000/5000 [==============================] - 0s 95us/step - loss: 0.9997 - mean_absolute_error: 0.7989 - mean_squared_error: 0.9997
Epoch 5/100
5000/5000 [==============================] - 0s 100us/step - loss: 0.9967 - mean_absolute_error: 0.7976 - mean_squared_error: 0.9967
Epoch 6/100
5000/5000 [==============================] - 0s 93us/step - loss: 0.9960 - mean_absolute_error: 0.7972 - mean_squared_error: 0.9960
Epoch 7/100
5000/5000 [==============================] - 0s 96us/step - loss: 0.9949 - mean_absolute_error: 0.7970 - mean_squared_erro

## Compute the sensitivities

In [53]:
# Assume that the activation function is tanh
def sensitivities(lm, X):
    
    W1=lm.model.get_weights()[0]
    b1=lm.model.get_weights()[1]
    W2=lm.model.get_weights()[2]
    b2=lm.model.get_weights()[3]
    
    
    M = np.shape(X)[0]
    p = np.shape(X)[1]

    beta=np.array([0]*M*(p+1), dtype='float32').reshape(M,p+1)
    
    beta[:,0]= (np.dot(np.transpose(W2),np.tanh(b1)) + b2)[0] # intercept \beta_0= F_{W,b}(0)
    for i in range(M):
 
      Z1 = np.tanh(np.dot(np.transpose(W1),np.transpose(X[i,])) + b1)
      #Z1 = np.maximum(np.dot(np.transpose(W1),np.transpose(X[i,])) + b1,0) 
      
      D = np.diag(1-Z1**2)
      #D = np.diag(np.sign(Z1))  
        
      for j in range(p):  
          beta[i,j+1]=np.dot(np.transpose(W2),np.dot(D,W1[j]))
            
    return(beta)

In [54]:
beta=sensitivities(lm, X)

## Check that the intercept is close to one and the coefficients are close to one

In [55]:
print(np.mean(beta, axis=0))

[-0.0288713   0.9822788   0.98537195]


In [56]:
print(np.std(beta, axis=0))

[1.8812773e-06 5.4207556e-02 5.4662943e-02]
